/*
 * Microshared-CRUD
 *
 * CRUD operation over Entities.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"os"

	sharedserver "sharedcrud/api"
	restAPI "sharedcrud/cmd/sharedcrud-server"
	gdbmanager "sharedcrud/gormdb"
)

//using two grpc servers linked in the same binary with same message names (GetRequest, GetReply, etc...)
//can cause issues during application runtime.
func startService(serviceName string) {
	gdbmanager.CurrentAppConfig = serviceName
	switch serviceName {
	case "alpha":
		go sharedserver.StartAlphaGRPC()
	case "beta":
		go sharedserver.StartBetaGRPC()
	default:
		log.Printf("unknown microservice role specified")
		return
	}
	restAPI.Entry()
}

func main() {
	if len(os.Args) < 2 {
		log.Println("Specify microservice role as command-line argument")
		return
	}
	startService(os.Args[1])
}
