/*
 * Microshared-CRUD
 *
 * CRUD operation over Entities.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net"
	"os"

	sharedserver "sharedcrud/api"
	alpharpc "sharedcrud/apirpc/alpha"
	betarpc "sharedcrud/apirpc/beta"
	restAPI "sharedcrud/cmd/sharedcrud-server"
	gdbmanager "sharedcrud/gormdb"

	"google.golang.org/grpc"
)

func startAlphaGRPC() {
	s := grpc.NewServer()
	srv := &sharedserver.AlphaGRPCServer{}
	alpharpc.RegisterAlphaCRUDRPCServer(s, srv)
	conn, err := net.Listen("tcp", ":8000")
	if err != nil {
		log.Fatal(err.Error())
	}
	if err := s.Serve(conn); err != nil {
		log.Fatal(err.Error())
	}

}

func startBetaGRPC() {
	s := grpc.NewServer()
	srv := &sharedserver.BetaGRPCServer{}
	betarpc.RegisterBetaCRUDRPCServer(s, srv)
	conn, err := net.Listen("tcp", ":8001")
	if err != nil {
		log.Fatal(err.Error())
	}
	if err := s.Serve(conn); err != nil {
		log.Fatal(err.Error())
	}

}

//using two grpc servers linked in the same binary with same message names (GetRequest, GetReply, etc...)
//can cause issues during application runtime.
func startService(serviceName string) {
	gdbmanager.CurrentAppConfig = serviceName
	switch serviceName {
	case "alpha":
		go startAlphaGRPC()
	case "beta":
		go startBetaGRPC()
	default:
		log.Printf("unknown microservice role specified")
		return
	}
	restAPI.Entry()
}

func main() {
	if len(os.Args) < 2 {
		log.Println("Specify microservice role as command-line argument")
		return
	}
	startService(os.Args[1])
}
