// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: apirpc/alpha-crud-grpc.proto

package alpharpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlphaUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Status      string `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *AlphaUpdateRequest) Reset() {
	*x = AlphaUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_alpha_crud_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlphaUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlphaUpdateRequest) ProtoMessage() {}

func (x *AlphaUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_alpha_crud_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlphaUpdateRequest.ProtoReflect.Descriptor instead.
func (*AlphaUpdateRequest) Descriptor() ([]byte, []int) {
	return file_apirpc_alpha_crud_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *AlphaUpdateRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AlphaUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlphaUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AlphaUpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AlphaUpdateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AlphaUpdateReply) Reset() {
	*x = AlphaUpdateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_alpha_crud_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlphaUpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlphaUpdateReply) ProtoMessage() {}

func (x *AlphaUpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_alpha_crud_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlphaUpdateReply.ProtoReflect.Descriptor instead.
func (*AlphaUpdateReply) Descriptor() ([]byte, []int) {
	return file_apirpc_alpha_crud_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *AlphaUpdateReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AlphaGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityName string `protobuf:"bytes,1,opt,name=entityName,proto3" json:"entityName,omitempty"`
}

func (x *AlphaGetRequest) Reset() {
	*x = AlphaGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_alpha_crud_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlphaGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlphaGetRequest) ProtoMessage() {}

func (x *AlphaGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_alpha_crud_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlphaGetRequest.ProtoReflect.Descriptor instead.
func (*AlphaGetRequest) Descriptor() ([]byte, []int) {
	return file_apirpc_alpha_crud_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *AlphaGetRequest) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

// The response message containing the greetings
type AlphaGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Status      string `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *AlphaGetReply) Reset() {
	*x = AlphaGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_alpha_crud_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlphaGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlphaGetReply) ProtoMessage() {}

func (x *AlphaGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_alpha_crud_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlphaGetReply.ProtoReflect.Descriptor instead.
func (*AlphaGetReply) Descriptor() ([]byte, []int) {
	return file_apirpc_alpha_crud_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *AlphaGetReply) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AlphaGetReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlphaGetReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AlphaGetReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_apirpc_alpha_crud_grpc_proto protoreflect.FileDescriptor

var file_apirpc_alpha_crud_grpc_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2d, 0x63,
	0x72, 0x75, 0x64, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x6d, 0x61, 0x69, 0x6e, 0x22, 0x72, 0x0a, 0x12, 0x41, 0x6c, 0x70, 0x68, 0x61, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2a, 0x0a, 0x10, 0x41, 0x6c, 0x70, 0x68,
	0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x31, 0x0a, 0x0f, 0x41, 0x6c, 0x70, 0x68, 0x61, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x6d, 0x0a, 0x0d, 0x41, 0x6c, 0x70, 0x68, 0x61,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xa1, 0x01, 0x0a, 0x0c, 0x41, 0x6c, 0x70, 0x68, 0x61,
	0x43, 0x52, 0x55, 0x44, 0x52, 0x50, 0x43, 0x12, 0x43, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x70, 0x68, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x6c, 0x70, 0x68, 0x61, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x6c, 0x70,
	0x68, 0x61, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x16,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x70, 0x68, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x6c,
	0x70, 0x68, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x6c, 0x70, 0x68, 0x61, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x63, 0x72, 0x75, 0x64, 0x2f, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apirpc_alpha_crud_grpc_proto_rawDescOnce sync.Once
	file_apirpc_alpha_crud_grpc_proto_rawDescData = file_apirpc_alpha_crud_grpc_proto_rawDesc
)

func file_apirpc_alpha_crud_grpc_proto_rawDescGZIP() []byte {
	file_apirpc_alpha_crud_grpc_proto_rawDescOnce.Do(func() {
		file_apirpc_alpha_crud_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_apirpc_alpha_crud_grpc_proto_rawDescData)
	})
	return file_apirpc_alpha_crud_grpc_proto_rawDescData
}

var file_apirpc_alpha_crud_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apirpc_alpha_crud_grpc_proto_goTypes = []interface{}{
	(*AlphaUpdateRequest)(nil), // 0: main.AlphaUpdateRequest
	(*AlphaUpdateReply)(nil),   // 1: main.AlphaUpdateReply
	(*AlphaGetRequest)(nil),    // 2: main.AlphaGetRequest
	(*AlphaGetReply)(nil),      // 3: main.AlphaGetReply
}
var file_apirpc_alpha_crud_grpc_proto_depIdxs = []int32{
	2, // 0: main.AlphaCRUDRPC.GetAlphaInformation:input_type -> main.AlphaGetRequest
	0, // 1: main.AlphaCRUDRPC.UpdateAlphaInformation:input_type -> main.AlphaUpdateRequest
	3, // 2: main.AlphaCRUDRPC.GetAlphaInformation:output_type -> main.AlphaGetReply
	1, // 3: main.AlphaCRUDRPC.UpdateAlphaInformation:output_type -> main.AlphaUpdateReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apirpc_alpha_crud_grpc_proto_init() }
func file_apirpc_alpha_crud_grpc_proto_init() {
	if File_apirpc_alpha_crud_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apirpc_alpha_crud_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlphaUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_alpha_crud_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlphaUpdateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_alpha_crud_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlphaGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_alpha_crud_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlphaGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apirpc_alpha_crud_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apirpc_alpha_crud_grpc_proto_goTypes,
		DependencyIndexes: file_apirpc_alpha_crud_grpc_proto_depIdxs,
		MessageInfos:      file_apirpc_alpha_crud_grpc_proto_msgTypes,
	}.Build()
	File_apirpc_alpha_crud_grpc_proto = out.File
	file_apirpc_alpha_crud_grpc_proto_rawDesc = nil
	file_apirpc_alpha_crud_grpc_proto_goTypes = nil
	file_apirpc_alpha_crud_grpc_proto_depIdxs = nil
}
