// Code generated by go-swagger; DO NOT EDIT.

package entity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewEntityGetParams creates a new EntityGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEntityGetParams() *EntityGetParams {
	return &EntityGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEntityGetParamsWithTimeout creates a new EntityGetParams object
// with the ability to set a timeout on a request.
func NewEntityGetParamsWithTimeout(timeout time.Duration) *EntityGetParams {
	return &EntityGetParams{
		timeout: timeout,
	}
}

// NewEntityGetParamsWithContext creates a new EntityGetParams object
// with the ability to set a context for a request.
func NewEntityGetParamsWithContext(ctx context.Context) *EntityGetParams {
	return &EntityGetParams{
		Context: ctx,
	}
}

// NewEntityGetParamsWithHTTPClient creates a new EntityGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewEntityGetParamsWithHTTPClient(client *http.Client) *EntityGetParams {
	return &EntityGetParams{
		HTTPClient: client,
	}
}

/* EntityGetParams contains all the parameters to send to the API endpoint
   for the entity get operation.

   Typically these are written to a http.Request.
*/
type EntityGetParams struct {

	/* EntityName.

	   Name of entity that need to be returned
	*/
	EntityName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the entity get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EntityGetParams) WithDefaults() *EntityGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the entity get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EntityGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the entity get params
func (o *EntityGetParams) WithTimeout(timeout time.Duration) *EntityGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the entity get params
func (o *EntityGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the entity get params
func (o *EntityGetParams) WithContext(ctx context.Context) *EntityGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the entity get params
func (o *EntityGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the entity get params
func (o *EntityGetParams) WithHTTPClient(client *http.Client) *EntityGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the entity get params
func (o *EntityGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEntityName adds the entityName to the entity get params
func (o *EntityGetParams) WithEntityName(entityName string) *EntityGetParams {
	o.SetEntityName(entityName)
	return o
}

// SetEntityName adds the entityName to the entity get params
func (o *EntityGetParams) SetEntityName(entityName string) {
	o.EntityName = entityName
}

// WriteToRequest writes these params to a swagger request
func (o *EntityGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param entityName
	if err := r.SetPathParam("entityName", o.EntityName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
