// Code generated by go-swagger; DO NOT EDIT.

package entity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// EntityStoreReader is a Reader for the EntityStore structure.
type EntityStoreReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EntityStoreReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEntityStoreOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 405:
		result := NewEntityStoreMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEntityStoreOK creates a EntityStoreOK with default headers values
func NewEntityStoreOK() *EntityStoreOK {
	return &EntityStoreOK{}
}

/* EntityStoreOK describes a response with status code 200, with default header values.

OK
*/
type EntityStoreOK struct {
}

func (o *EntityStoreOK) Error() string {
	return fmt.Sprintf("[POST /entity][%d] entityStoreOK ", 200)
}

func (o *EntityStoreOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEntityStoreMethodNotAllowed creates a EntityStoreMethodNotAllowed with default headers values
func NewEntityStoreMethodNotAllowed() *EntityStoreMethodNotAllowed {
	return &EntityStoreMethodNotAllowed{}
}

/* EntityStoreMethodNotAllowed describes a response with status code 405, with default header values.

Invalid input
*/
type EntityStoreMethodNotAllowed struct {
}

func (o *EntityStoreMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /entity][%d] entityStoreMethodNotAllowed ", 405)
}

func (o *EntityStoreMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
