// Code generated by go-swagger; DO NOT EDIT.

package entity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"test-server/models"
)

// NewEntityStoreParams creates a new EntityStoreParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEntityStoreParams() *EntityStoreParams {
	return &EntityStoreParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEntityStoreParamsWithTimeout creates a new EntityStoreParams object
// with the ability to set a timeout on a request.
func NewEntityStoreParamsWithTimeout(timeout time.Duration) *EntityStoreParams {
	return &EntityStoreParams{
		timeout: timeout,
	}
}

// NewEntityStoreParamsWithContext creates a new EntityStoreParams object
// with the ability to set a context for a request.
func NewEntityStoreParamsWithContext(ctx context.Context) *EntityStoreParams {
	return &EntityStoreParams{
		Context: ctx,
	}
}

// NewEntityStoreParamsWithHTTPClient creates a new EntityStoreParams object
// with the ability to set a custom HTTPClient for a request.
func NewEntityStoreParamsWithHTTPClient(client *http.Client) *EntityStoreParams {
	return &EntityStoreParams{
		HTTPClient: client,
	}
}

/* EntityStoreParams contains all the parameters to send to the API endpoint
   for the entity store operation.

   Typically these are written to a http.Request.
*/
type EntityStoreParams struct {

	/* Body.

	   Entity object that needs to be stored
	*/
	Body *models.Entity

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the entity store params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EntityStoreParams) WithDefaults() *EntityStoreParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the entity store params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EntityStoreParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the entity store params
func (o *EntityStoreParams) WithTimeout(timeout time.Duration) *EntityStoreParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the entity store params
func (o *EntityStoreParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the entity store params
func (o *EntityStoreParams) WithContext(ctx context.Context) *EntityStoreParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the entity store params
func (o *EntityStoreParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the entity store params
func (o *EntityStoreParams) WithHTTPClient(client *http.Client) *EntityStoreParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the entity store params
func (o *EntityStoreParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the entity store params
func (o *EntityStoreParams) WithBody(body *models.Entity) *EntityStoreParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the entity store params
func (o *EntityStoreParams) SetBody(body *models.Entity) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *EntityStoreParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
