// Code generated by go-swagger; DO NOT EDIT.

package entity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// EntityDeleteOKCode is the HTTP code returned for type EntityDeleteOK
const EntityDeleteOKCode int = 200

/*EntityDeleteOK OK

swagger:response entityDeleteOK
*/
type EntityDeleteOK struct {
}

// NewEntityDeleteOK creates EntityDeleteOK with default headers values
func NewEntityDeleteOK() *EntityDeleteOK {

	return &EntityDeleteOK{}
}

// WriteResponse to the client
func (o *EntityDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// EntityDeleteNotFoundCode is the HTTP code returned for type EntityDeleteNotFound
const EntityDeleteNotFoundCode int = 404

/*EntityDeleteNotFound No entity was found

swagger:response entityDeleteNotFound
*/
type EntityDeleteNotFound struct {
}

// NewEntityDeleteNotFound creates EntityDeleteNotFound with default headers values
func NewEntityDeleteNotFound() *EntityDeleteNotFound {

	return &EntityDeleteNotFound{}
}

// WriteResponse to the client
func (o *EntityDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
