// Code generated by go-swagger; DO NOT EDIT.

package entity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"sharedcrud/models"
)

// EntityGetOKCode is the HTTP code returned for type EntityGetOK
const EntityGetOKCode int = 200

/*EntityGetOK successful operation

swagger:response entityGetOK
*/
type EntityGetOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Entity `json:"body,omitempty"`
}

// NewEntityGetOK creates EntityGetOK with default headers values
func NewEntityGetOK() *EntityGetOK {

	return &EntityGetOK{}
}

// WithPayload adds the payload to the entity get o k response
func (o *EntityGetOK) WithPayload(payload []*models.Entity) *EntityGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the entity get o k response
func (o *EntityGetOK) SetPayload(payload []*models.Entity) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EntityGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Entity, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// EntityGetNotFoundCode is the HTTP code returned for type EntityGetNotFound
const EntityGetNotFoundCode int = 404

/*EntityGetNotFound No entity was found

swagger:response entityGetNotFound
*/
type EntityGetNotFound struct {
}

// NewEntityGetNotFound creates EntityGetNotFound with default headers values
func NewEntityGetNotFound() *EntityGetNotFound {

	return &EntityGetNotFound{}
}

// WriteResponse to the client
func (o *EntityGetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
