// Code generated by go-swagger; DO NOT EDIT.

package entity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// EntityStoreHandlerFunc turns a function with the right signature into a entity store handler
type EntityStoreHandlerFunc func(EntityStoreParams) middleware.Responder

// Handle executing the request and returning a response
func (fn EntityStoreHandlerFunc) Handle(params EntityStoreParams) middleware.Responder {
	return fn(params)
}

// EntityStoreHandler interface for that can handle valid entity store params
type EntityStoreHandler interface {
	Handle(EntityStoreParams) middleware.Responder
}

// NewEntityStore creates a new http.Handler for the entity store operation
func NewEntityStore(ctx *middleware.Context, handler EntityStoreHandler) *EntityStore {
	return &EntityStore{Context: ctx, Handler: handler}
}

/* EntityStore swagger:route POST /entity entity entityStore

Add a new Entity if such Name is not exists. Update otherwise

*/
type EntityStore struct {
	Context *middleware.Context
	Handler EntityStoreHandler
}

func (o *EntityStore) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewEntityStoreParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
