// Code generated by go-swagger; DO NOT EDIT.

package entity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// EntityStoreOKCode is the HTTP code returned for type EntityStoreOK
const EntityStoreOKCode int = 200

/*EntityStoreOK OK

swagger:response entityStoreOK
*/
type EntityStoreOK struct {
}

// NewEntityStoreOK creates EntityStoreOK with default headers values
func NewEntityStoreOK() *EntityStoreOK {

	return &EntityStoreOK{}
}

// WriteResponse to the client
func (o *EntityStoreOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// EntityStoreMethodNotAllowedCode is the HTTP code returned for type EntityStoreMethodNotAllowed
const EntityStoreMethodNotAllowedCode int = 405

/*EntityStoreMethodNotAllowed Invalid input

swagger:response entityStoreMethodNotAllowed
*/
type EntityStoreMethodNotAllowed struct {
}

// NewEntityStoreMethodNotAllowed creates EntityStoreMethodNotAllowed with default headers values
func NewEntityStoreMethodNotAllowed() *EntityStoreMethodNotAllowed {

	return &EntityStoreMethodNotAllowed{}
}

// WriteResponse to the client
func (o *EntityStoreMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
