// Code generated by go-swagger; DO NOT EDIT.

package entity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewEntityHandlerParams creates a new EntityHandlerParams object
//
// There are no default values defined in the spec.
func NewEntityHandlerParams() EntityHandlerParams {

	return EntityHandlerParams{}
}

// EntityHandlerParams contains all the bound params for the entity handler operation
// typically these are obtained from a http.Request
//
// swagger:parameters entityHandler
type EntityHandlerParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Name of entity that need to be returned
	  Required: true
	  In: path
	*/
	EntityName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewEntityHandlerParams() beforehand.
func (o *EntityHandlerParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rEntityName, rhkEntityName, _ := route.Params.GetOK("entityName")
	if err := o.bindEntityName(rEntityName, rhkEntityName, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEntityName binds and validates parameter EntityName from path.
func (o *EntityHandlerParams) bindEntityName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.EntityName = raw

	return nil
}
